export const polaroidCopy = {
  en: {
    title: 'The keepsake studio', eyebrow: 'ALEEM & NURULAIN · 21–22 AUGUST 2027', heading: 'A moment,', headingEm: 'made to keep.',
    intro: 'Your favourite photo. A frame from our story. A little piece of forever to take home.', back: 'Back to gallery',
    preview: 'Your Polaroid preview', emptyTitle: 'This moment is yours.', emptyBody: 'Add a photo or step into the booth.', choose: 'Choose a photo', camera: 'Open camera', replace: 'Change photo',
    sourceLabel: 'Your photograph', formats: 'JPG, PNG, WebP or HEIC · up to 25 MB', privacy: 'Made on your device. Only uploaded if you choose “Add to gallery”.',
    frame: 'Choose your frame', ivory: 'Ivory vows', airmail: 'Love, airmail', clouds: 'Above the clouds',
    finish: 'Set the mood', original: 'Natural', warm: 'Warm film', mono: 'Black & white',
    details: 'Make it yours', caption: 'A little caption', captionPlaceholder: 'A day to remember…', optional: 'optional', date: 'The celebration', both: 'Our wedding · 21–22 August', dayOne: '21 August · Nikah & Bride’s Reception', dayTwo: '22 August · Groom’s Reception',
    crop: 'Fine-tune the photo', drag: 'Drag your photo to find the perfect crop.', keyboardCrop: 'Use arrow keys to move the crop, or use the sliders below.', zoom: 'Zoom', horizontal: 'Left / right', vertical: 'Up / down', rotate: 'Rotate photo', reset: 'Reset crop',
    save: 'Save PNG', upload: 'Add to gallery', preparing: 'Making your keepsake…', loading: 'Opening your photo…', rendering: 'Developing your preview…',
    output: '1200 × 1500 pixels · Your frame and caption included', saved: 'Your keepsake is ready. Check your downloads.', uploadNote: 'Photos added to the gallery appear after approval.',
    loadError: 'This photo could not be opened. Try another JPG, PNG or WebP image.', sizeError: 'Choose a photo smaller than 25 MB.', formatError: 'Choose a JPG, PNG, WebP or HEIC photo.',
    renderError: 'The preview could not be prepared. Please try again.', exportError: 'Your keepsake could not be saved. Please try again.', retry: 'Try again',
  },
  ms: {
    title: 'Studio kenangan', eyebrow: 'ALEEM & NURULAIN · 21–22 OGOS 2027', heading: 'Satu detik,', headingEm: 'untuk dikenang.',
    intro: 'Foto kegemaran anda. Bingkai daripada kisah kami. Kenangan kecil untuk dibawa pulang.', back: 'Kembali ke galeri',
    preview: 'Pratonton Polaroid anda', emptyTitle: 'Detik ini milik anda.', emptyBody: 'Pilih foto atau gunakan kamera.', choose: 'Pilih foto', camera: 'Buka kamera', replace: 'Tukar foto',
    sourceLabel: 'Foto anda', formats: 'JPG, PNG, WebP atau HEIC · sehingga 25 MB', privacy: 'Dicipta pada peranti anda. Dimuat naik hanya jika anda memilih “Tambah ke galeri”.',
    frame: 'Pilih bingkai anda', ivory: 'Janji cinta', airmail: 'Kiriman kasih', clouds: 'Di atas awan',
    finish: 'Pilih suasana', original: 'Asli', warm: 'Filem hangat', mono: 'Hitam putih',
    details: 'Sentuhan peribadi', caption: 'Kapsyen ringkas', captionPlaceholder: 'Hari untuk dikenang…', optional: 'pilihan', date: 'Majlis', both: 'Perkahwinan kami · 21–22 Ogos', dayOne: '21 Ogos · Nikah & Resepsi Pengantin Perempuan', dayTwo: '22 Ogos · Resepsi Pengantin Lelaki',
    crop: 'Laraskan foto', drag: 'Seret foto untuk mendapatkan potongan yang sesuai.', keyboardCrop: 'Gunakan kekunci anak panah atau peluncur di bawah untuk mengubah kedudukan foto.', zoom: 'Zum', horizontal: 'Kiri / kanan', vertical: 'Atas / bawah', rotate: 'Putar foto', reset: 'Set semula',
    save: 'Simpan PNG', upload: 'Tambah ke galeri', preparing: 'Menyediakan kenangan anda…', loading: 'Membuka foto anda…', rendering: 'Menyediakan pratonton…',
    output: '1200 × 1500 piksel · Termasuk bingkai dan kapsyen', saved: 'Kenangan anda tersedia. Semak muat turun anda.', uploadNote: 'Foto yang ditambah ke galeri akan dipaparkan selepas diluluskan.',
    loadError: 'Foto ini tidak dapat dibuka. Cuba imej JPG, PNG atau WebP lain.', sizeError: 'Pilih foto yang lebih kecil daripada 25 MB.', formatError: 'Pilih foto JPG, PNG, WebP atau HEIC.',
    renderError: 'Pratonton tidak dapat disediakan. Sila cuba lagi.', exportError: 'Kenangan anda tidak dapat disimpan. Sila cuba lagi.', retry: 'Cuba lagi',
  },
}
